### ISSUE TITLE
Add Monster AI

### ISSUE THREAD

**Issue by ghost** [melnig/sos#10]
We need some way for Monster objects to decide what they do on their turn during combat

One suggestion was to have random actions but that would make monsters unthreatening
Always picking the strongest move is creates boring gameplay unless monsters always generate with random Skill sets

**Comment by melngr** [comment]
Do we just want to do something very simple where we pick a random attack and it does some random amount of damage relative to player health/monster attack?

**Comment by ghost** [comment]
No Monster has a Skill set too.
The issue is how will the game select what Skill to use other than random.

Picking the strongest attack always makes the combat boring but random seems kinda boring too :(
